interface TestData {
  typeOfTest: string;
  testName: string;
  SumOfItemScores: number;
  BasalCredit: number;
  WlookUp: number;
  Wscore: number;
  semW: number;
  WlkpAdminItems: string;
  ScoreString: string;
  testStemForm: string;
  lookUpModel: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  totalItems: number;
  scoreFlag: string;
  BbyC?: number;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
}

  
  export const testData: TestData[] = [
    /* ----------------------ALL CORRECT-------------------------- */
    {
      typeOfTest: "Ages 4 to 7 - All correct scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 36,
      BasalCredit: 0,
      WlookUp: 36,
      Wscore: 568.5,
      semW: 15.28,
      WlkpAdminItems: "",
      ScoreString: "^111111111111111111111111111111111111",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 4 to 7",
      totalItems: 36,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 8 to 9 - All correct scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 33,
      BasalCredit: 3,
      WlookUp: 36,
      Wscore: 568.5,
      semW: 15.28,
      WlkpAdminItems: "",
      ScoreString: "^xxx111111111111111111111111111111111",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 8 to 9",
      totalItems: 33,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 10 to 11 - All correct scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 29,
      BasalCredit: 7,
      WlookUp: 36,
      Wscore: 568.5,
      semW: 15.28,
      WlkpAdminItems: "",
      ScoreString: "^xxxxxxx11111111111111111111111111111",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 10 to 11",
      totalItems: 29,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 12 to Average Adult - All correct scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 27,
      BasalCredit: 9,
      WlookUp: 36,
      Wscore: 568.5,
      semW: 15.28,
      WlkpAdminItems: "",
      ScoreString: "^xxxxxxxxx111111111111111111111111111",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 12 to Average Adult",
      totalItems: 27,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Above Average Adult - All correct scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 22,
      BasalCredit: 14,
      WlookUp: 36,
      Wscore: 568.5,
      semW: 15.28,
      WlkpAdminItems: "",
      ScoreString: "^xxxxxxxxxxxxxx1111111111111111111111",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Above Average Adult",
      totalItems: 22,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
     /* ----------------------ALL INCORRECT-------------------------- */
    {
      typeOfTest: "Ages 4 to 7 - All incorrect scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 0,
      BasalCredit: 0,
      WlookUp: 0,
      Wscore: 393.64,
      semW: 16.06,
      WlkpAdminItems: "",
      ScoreString: "^00000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 4 to 7",
      totalItems: 36,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 8 to 9 - All incorrect scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 0,
      BasalCredit: 0,
      WlookUp: 0,
      Wscore: 393.64,
      semW: 16.06,
      WlkpAdminItems: "",
      ScoreString: "^00000xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 8 to 9",
      totalItems: 33,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 10 to 11 - All incorrect scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 0,
      BasalCredit: 0,
      WlookUp: 0,
      Wscore: 393.64,
      semW: 16.06,
      WlkpAdminItems: "",
      ScoreString: "^00000xx0xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 10 to 11",
      totalItems: 29,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Ages 12 to Average Adult - All incorrect scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 0,
      BasalCredit: 0,
      WlookUp: 0,
      Wscore: 393.64,
      semW: 16.06,
      WlkpAdminItems: "",
      ScoreString: "^00000xxxx0xxxxxxxxxxxxxxxxxxxxxxxxxx",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Ages 12 to Average Adult",
      totalItems: 27,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
    {
      typeOfTest: "Above Average Adult - All incorrect scenario",
      testName: "Academic Vocabulary",
      SumOfItemScores: 0,
      BasalCredit: 0,
      WlookUp: 0,
      Wscore: 393.64,
      semW: 16.06,
      WlkpAdminItems: "",
      ScoreString: "^00000xxxx0xxxx0xxxxxxxxxxxxxxxxxxxxx",
      testStemForm: "ACDVOC.W5PA",
      lookUpModel: "SingleTable",
      blockName: "Form A",
      examineeAge: 4,
      SSP: "Above Average Adult",
      totalItems: 22,
      scoreFlag: "",
      location: "PVP",
      examineeGrade: "Grade 4",
    },
  ];
  