interface TestData {
  typeOfTest: string;
  testName: string;
  testStemForm: string;
  lookUpModel: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  totalItems: number;
  scoreFlag: string;
  location?: string;
  BbyC?: number;
  negation?: boolean;
  examineeGrade?: string;
}

export const testData: TestData[] = [
  /* ----------------------ALL CORRECT-------------------------- */
  {
    typeOfTest: "Age 4 - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 4",
    totalItems: 47,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 5 to 6 - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 5 to 6",
    totalItems: 38,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 7 to 8 - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 7 to 8",
    totalItems: 34,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 9 to 10 - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 9 to 10",
    totalItems: 32,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 11 to 14 - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 11 to 14",
    totalItems: 28,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 15 to Average Adult - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 15 to Average Adult",
    totalItems: 26,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Above Average Adult - All correct scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    totalItems: 20,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  /* ----------------------ALL INCORRECT-------------------------- */
  {
    typeOfTest: "Age 4 - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 4",
    totalItems: 47,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 5 to 6 - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 5 to 6",
    totalItems: 38,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 7 to 8 - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 7 to 8",
    totalItems: 34,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 9 to 10 - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 9 to 10",
    totalItems: 32,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 11 to 14 - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 11 to 14",
    totalItems: 30,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 15 to Average Adult - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 15 to Average Adult",
    totalItems: 26,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Above Average Adult - All incorrect scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    totalItems: 20,
    scoreFlag: "",
    location: "PublicationsOrg01",
    examineeGrade: "Grade 5",
  },
];
