interface TestData {
  typeOfTest: string;
  testName: string;
  testStemForm: string;
  lookUpModel: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  totalItems: number;
  scoreFlag: string;
  location?: string;
  BbyC?: number;
  negation?: boolean;
  examineeGrade?: string;
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 4 to 6 - All correct scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 6",
    totalItems: 35,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 7 - All correct scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 7",
    totalItems: 31,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 8 to 11 - All correct scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 8 to 11",
    totalItems: 26,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 12 to Average Adult - All correct scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 12 to Average Adult",
    totalItems: 23,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Above Average Adult - All correct scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    totalItems: 19,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 4 to 6 - All incorrect scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 6",
    totalItems: 35,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 7 - All incorrect scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 7",
    totalItems: 31,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Ages 8 to 11 - All incorrect scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 8 to 11",
    totalItems: 26,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Age 12 to Average Adult - All incorrect scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 12 to Average Adult",
    totalItems: 23,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
  {
    typeOfTest: "Above Average Adult - All incorrect scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    totalItems: 19,
    scoreFlag: "",
    location: "PVP",
    examineeGrade: "Grade 5",
  },
];
