interface TestData {
  typeOfTest: string;
  testName: string;
  testStemForm: string;
  lookUpModel: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
}

export const testData: TestData[] = [
  /*{
    typeOfTest: "All Examinees - ANLSYN Item 1 to 7 Scenario",
    testName: "Analysis-Synthesis",
    testStemForm: "ANLSYN.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees - ANLSYN Item 1 to 19 Scenario",
    testName: "Analysis-Synthesis",
    testStemForm: "ANLSYN.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },

  {
    typeOfTest: "All Examinees - ANLSYN Item 1 to 25 Scenario",
    testName: "Analysis-Synthesis",
    testStemForm: "ANLSYN.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },

  {
    typeOfTest: "All Examinees - ANLSYN Item 1 to 31 Scenario",
    testName: "Analysis-Synthesis",
    testStemForm: "ANLSYN.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees - ANLSYN Color Pretests End Test Scenario",
    testName: "Analysis-Synthesis",
    testStemForm: "ANLSYN.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 4 to 7 - STYCMP Sample Items to Block A rerouting End Test Scenario",
    testName: "Story Comprehension",
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 7 - STYCMP Block A End Test Scenario",
    testName: "Story Comprehension",
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 8 to 10 - STYCMP Block B to Block A rerouting End Test Scenario",
    testName: "Story Comprehension",
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 8 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 11 to 13 - STYCMP Block C to Block B rerouting End Test Scenario",
    testName: "Story Comprehension",
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Age 14 to Adult - STYCMP Block D to Block C rerouting End Test Scenario",
    testName: "Story Comprehension",
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 6 -  PARCMP Block A End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 6 -  PARCMP Block B End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Age 7 -  PARCMP Block B to Block A rerouting End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Age 7 -  PARCMP Block C End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Age 8 -  PARCMP Block C to Block B rerouting End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Age 8 -  PARCMP Block D End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 9 to Above Average Adult -  PARCMP Block D to Block C rerouting End Test Scenario",
    testName: "Paragraph Reading Comprehension",
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 5-  ORLSMP Block A End Test Scenario",
    testName: "Oral Language Samples",
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 6 to 7-  Block B to Block A ORLSMP rerouting End Test Scenario",
    testName: "Oral Language Samples",
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 11-  Block A MATRCZ End Test Scenario",
    testName: "Matrices",
    testStemForm: "MATRCZ.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 11-  Block A to Block C MATRCZ End Test Scenario",
    testName: "Matrices",
    testStemForm: "MATRCZ.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Age 6 -  Block C to Block A&B LWIDNT End Test Scenario",
    testName: "Letter-Word Identification",
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 5 -  LWIDNT Block A End Test Scenario",
    testName: "Letter-Word Identification",
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 7 -  WRDATK Block B End Test Scenario",
    testName: "Word Attack",
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 10 to 11 -  WRDATK Block C End Test Scenario",
    testName: "Word Attack",
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 6 -  PSGCMP Block A End Test Scenario",
    testName: "Passage Comprehension",
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees -  WRDGFL Practice Exercise End Test Scenario",
    testName: "Word Reading Fluency",
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees -  NUMPAT Sample Items End Test Scenario",
    testName: "Number-Pattern Matching",
    testStemForm: "NUMPAT.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees -  SRDGFL Practice Exercise End Test Scenario",
    testName: "Sentence Reading Fluency",
    testStemForm: "SRDGFL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees -  SYMBIN Sample Items End Test Scenario",
    testName: "Symbol Inhibition",
    testStemForm: "SYMBIN.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Above Average Adult -  OVSYN next item check Scenario",
    testName: "Oral Vocabulary–Synonyms",
    testStemForm: "OVSYN.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Above Average Adult -  OVANT next item check when response changed Scenario",
    testName: "Oral Vocabulary–Antonyms",
    testStemForm: "OVANT.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Ages 11 to 14 -  PICVOC next item check when response changed Scenario",
    testName: "Picture Vocabulary",
    testStemForm: "PICVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 11 to 14",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Age 9 -  APPROB lowest numbered unadministered item rerouting Scenario",
    testName: "Applied Problems",
    testStemForm: "APPROB.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 9",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 10 to 11 -  CALC basal break rerouting Scenario",
    testName: "Calculation",
    testStemForm: "CALC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 14 to Adult -  SNDREV Ceiling break rerouting Scenario",
    testName: "Sound Reversal",
    testStemForm: "SNDREV.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 11 to 13 -  MPRBID Ceiling break rerouting Scenario",
    testName: "Math Problem Identification",
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 9 to 11 -  GIWHAT Ceiling break rerouting Scenario",
    testName: "General Information–What",
    testStemForm: "GIWHAT.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Above Average Adult -  GIWHER Ceiling break rerouting Scenario",
    testName: "General Information–Where",
    testStemForm: "GIWHER.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Age 12 to Adult -  NWDREP Ceiling break rerouting Scenario",
    testName: "Nonsense Word Repetition",
    testStemForm: "NWDREP.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 12 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest:
      "Above Average Adult -  VRBANL Ceiling break rerouting Scenario",
    testName: "Verbal Analogies",
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },*/
  {
    typeOfTest: "Ages 4 to 5 -  SNDDEL Block A End Test Scenario",
    testName: "Sound Deletion",
    testStemForm: "SNDDEL.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Age 6 -  SNDDEL Block B End Test Scenario",
    testName: "Sound Deletion",
    testStemForm: "SNDDEL.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 7 to Adult -  SNDDEL Block C End Test Scenario",
    testName: "Sound Deletion",
    testStemForm: "SNDDEL.W5PA",
    lookUpModel: "Multitable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examines -  LETPAT Sample Items End Test Scenario",
    testName: "Letter-Pattern Matching",
    testStemForm: "LETPAT.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "All Examinees -  LETPAT Sample Items End Test Scenario",
    testName: "Letter-Pattern Matching",
    testStemForm: "LETPAT.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 7 to 11 -  SNDBLN Ceiling break rerouting Scenario",
    testName: "Sound Blending",
    testStemForm: "SNDBLN.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 7 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
   
  {
    typeOfTest: "Ages 4 to 7 -  MEMWRD Ceiling break rerouting Scenario",
    testName: "Memory for Words",
    testStemForm: "MEMWRD.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
  {
    typeOfTest: "Ages 4 to 7 -  ACDVOC Ceiling break rerouting Scenario",
    testName: "Academic Vocabulary",
    testStemForm: "ACDVOC.W5PA",
    lookUpModel: "SingleTable",
    blockName: "Form A",
    examineeAge: 4,
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
  },
];
