interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 7 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 7 - Basal and ceiling with 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 -  5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y1m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 - All correct scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">29y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 - Review flow Scenario for SSP1",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    /*---------------------------------------------Ages 8 to 9 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 8 to 9 - Basal and ceiling with 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 8 to 9 -  5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "6y4m",
        GE: "GK.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 8 to 9 - Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "6y4m",
        GE: "GK.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 8 to 9 - All correct scenario ",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">29y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 8 to 9 - Review flow Scenario for SSP2",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    /*---------------------------------------------Ages 10 to 11 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 10 to 11 - Basal and ceiling with 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 -  5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "8y2m",
        GE: "G2.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "8y2m",
        GE: "G2.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 - All correct scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">29y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 - Review flow Scenario for SSP3",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
     /*---------------------------------------------Ages 12 to Average Adult Scenarios---------------------------------------------------*/
     {
        typeOfTest: "Ages 12 to Average Adult - Basal and ceiling with 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 12 to Average Adult -  5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "9y1m",
        GE: "G3.7",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 12 to Average Adult-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "9y1m",
        GE: "G3.7",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 12 to Average Adult - All correct scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">29y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Ages 12 to Average Adult - Review flow Scenario for SSP4",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
     /*---------------------------------------------Above Average Adult Scenarios---------------------------------------------------*/
     {
        typeOfTest: "Above Average Adult - Basal and ceiling with 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Above Average Adult -  5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "12y2m",
        GE: "G6.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Above Average Adult-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "12y2m",
        GE: "G6.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Above Average Adult - All correct scenario",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">29y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
    {
        typeOfTest: "Above Average Adult - Review flow Scenario for SSP5",
        testName: "Academic Vocabulary",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ACDVOC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Displayed good knowledge of content area vocabulary",
            "Had difficulty retrieving words",
            "Displayed limited knowledge of content area vocabulary",
            "Displayed age-appropriate speech and articulation",
            "Expressed oral responses with ease",
            "Did not display age-appropriate speech and articulation",
            "Had difficulty expressing oral responses",
            "None of the above",
            "Retrieved words fluently",
        ],
    },
]