interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string;
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
  }
  
  export const testData: TestData[] = [
    {
        typeOfTest: "All Examinees - Color Pretest End Test Flow scenario",
        testName: "Analysis-Synthesis",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "ANLSYN.W5PA",
        lookUpModel: "Multitable",
        SSP: "All Examinees",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee did not pass the Color Pretest.",
        responseStyleBehaviours: [
          "Easily comprehended long, complex verbal instructions",
          "Displayed cognitive flexibility when moving between different item types/sets",
          "Appeared to have difficulty comprehending long, complex verbal instructions",
          "Verbalized insight into underlying math logic system",
          "Appeared to benefit from corrective feedback",
          "Controlled frustration level as the items increased in difficulty",
          "Used “self-talk” strategy",
          "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - All incorrect scenario",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "<4y0m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - All correct scenario",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">22y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - End Test scenario when test ends at item 19",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "4y9m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - End Test scenario when test ends at item 25",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "6y2m",
      GE: "GK.7",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - End Test scenario when test ends at item 31",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "7y8m",
      GE: "G2.3",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Review flow Scenario",
      testName: "Analysis-Synthesis",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "ANLSYN.W5PA",
      lookUpModel: "Multitable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "9y8m",
      GE: "G4.2",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Easily comprehended long, complex verbal instructions",
        "Displayed cognitive flexibility when moving between different item types/sets",
        "Appeared to have difficulty comprehending long, complex verbal instructions",
        "Verbalized insight into underlying math logic system",
        "Appeared to benefit from corrective feedback",
        "Controlled frustration level as the items increased in difficulty",
        "Used “self-talk” strategy",
        "None of the above",
      ],
    },
  ];
  