interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 6 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 6 - Sample Items End Test Flow scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 6",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee did not meet continuation requirements.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 4 to 6 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 6",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 4 to 6 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 6",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "5y4m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 4 to 6 - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 6",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 4 to 6 - Review flow Scenario for SSP1",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 6",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Age 7 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Age 7 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 7 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "6y5m",
        GE: "G1.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 7 - Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "6y5m",
        GE: "G1.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 7 - All correct scenario ",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 7 - Review flow Scenario for SSP2",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Age 8 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Age 8 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 8 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "7y1m",
        GE: "G1.7",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 8-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "7y1m",
        GE: "G1.7",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 8 - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 8 - Review flow Scenario for SSP3",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Age 9 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Age 9 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 9 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "7y10m",
        GE: "G2.4",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 9-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "7y10m",
        GE: "G2.4",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 9 - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Age 9 - Review flow Scenario for SSP4",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 9",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Ages 10 to 11 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 10 to 11 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "8y9m",
        GE: "G3.4",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "8y9m",
        GE: "G3.4",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 10 to 11 - Review flow Scenario for SSP5",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 10 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Ages 12 to 13 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 12 to 13 - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 12 to 13 -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "9y11m",
        GE: "G4.5",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 12 to 13-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "9y11m",
        GE: "G4.5",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 12 to 13 - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 12 to 13 - Review flow Scenario for SSP6",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    /*---------------------------------------------Ages 14 to Adult Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 14 to Adult - Basal and ceiling with 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult -  5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "11y2m",
        GE: "G5.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult-  Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "11y2m",
        GE: "G5.8",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult - All correct scenario",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">24y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult - Review flow Scenario for SSP7",
        testName: "Calculation",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "CALC.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Solved attempted problems quickly",
            "Used strategies that were inefficient or inappropriate for age/grade (e.g., finger counting)",
            "Solved attempted problems slowly",
            "Made conceptual errors (e.g., confused addition and subtraction signs, made regrouping errors)",
            "Made errors on several math facts",
            "None of the above",
            "Used strategies that were efficient and appropriate for age/grade",
        ],
    },
]