interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 5 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 5 - Basal and ceiling with 4 incorrect scenario SSP1",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 5",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 5 -  4 correct and 4 incorrect scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 5",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 5 - All correct scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 5",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    /*---------------------------------------------Ages 6 to 8 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 6 to 8 -  4 correct and 4 incorrect scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 6 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 6 to 8 - Reverse logic with 4 incorrect scenario SSP2",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 6 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 6 to 8 - All correct scenario ",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 6 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    /*---------------------------------------------Ages 9 to 11 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 9 to 11 -  4 correct and 4 incorrect scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 9 to 11 - Reverse logic with 4 incorrect scenario SSP3",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 9 to 11 - All correct scenario ",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 11",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
     /*---------------------------------------------Ages 12 to 14 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 12 to 14 -  4 correct and 4 incorrect scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 14",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 12 to 14 - Reverse logic with 4 incorrect scenario SSP4",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 14",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 12 to 14 - All correct scenario ",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 12 to 14",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    /*---------------------------------------------Age 15 to Adult Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Age 15 to Adult -  4 correct and 4 incorrect scenario",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 15 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Age 15 to Adult - Reverse logic with 4 incorrect scenario SSP5",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 15 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Age 15 to Adult - All correct scenario ",
        testName: "General Information–What",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "GIWHAT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 15 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
]
