interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Block A EndTest Flow when RS is 0",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Block A forward flow scenario when RS is 1",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block AB EndTest flow scenario when RS is 9",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y1m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Block AB to C Forward flow scenario when RS is 10",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "All Correct SSP 1",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 6",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 6 Basal & Ceiling scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y7m",
    GE: "GK.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 7 Basal & Ceiling scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y6m",
    GE: "G1.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 8 Basal & Ceiling scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y2m",
    GE: "G1.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Ages 9 to 11 Basal & Ceiling scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y0m",
    GE: "G2.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 12 to Adult Basal & Ceiling scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y5m",
    GE: "G4.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 6 Review Flow Scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Age 7 Review Flow Scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Age 8 Review Flow Scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 9 to 11 Review Flow Scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Age 12 to Adult Review Flow Scenario",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y11m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y11m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y11m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Letter-Word Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "LWIDNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y11m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Pronounced initial sounds of some words correctly but appeared to guess at the remaining sounds",
      "Had difficulty reading word(s) smoothly as whole word(s)",
      "Applied phonics to unfamiliar words",
      "Read grade-appropriate items accurately with ease",
      "Had difficulty applying phonics to unfamiliar words",
      "Had difficulty reading grade-appropriate items accurately with ease",
      "None of the above",
    ],
  },
];
