interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 7 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 7 - Basal and ceiling with 4 incorrect scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 -  4 correct and 4 incorrect scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 - All correct scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">22y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 4 to 7 - Review flow Scenario for SSP1",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 7",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    /*---------------------------------------------Ages 8 to Adult Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 8 to Adult - Basal and ceiling with 4 incorrect scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 8 to Adult -  4 correct and 4 incorrect scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "5y7m",
        GE: "GK.1",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 8 to Adult - Reverse logic with 4 correct and 4 incorrect scenario",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "5y7m",
        GE: "GK.1",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 8 to Adult - All correct scenario ",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">22y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
    {
        typeOfTest: "Ages 8 to Adult - Review flow Scenario for SSP2",
        testName: "Memory for Words",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "MEMWRD.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 8 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "<4y0m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Errors suggested good recall of stimuli but incorrect ordering",
            "Used “self-talkˮ strategy",
            "Errors suggested poor recall of stimuli but correct ordering",
            "None of the above",
            "Used memory strategies (e.g., rehearsal, chunking, elaboration, visualization, mnemonics)",
        ],
    },
     
]