interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "All Correct SSP 1",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "All Correct SSP 6",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP2",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP1",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y2m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP2",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y2m",
    GE: "GK.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP3",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y10m",
    GE: "G1.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP4",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y6m",
    GE: "G2.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP5",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y6m",
    GE: "G3.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "B&C SSP6",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y10m",
    GE: "G5.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Sample Items AB discontinue Scenario for SSP 1",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Sample Items AB discontinue Scenario for SSP 2",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },

  {
    typeOfTest: "Sample Items AB discontinue Scenario for SSP 3",
    testName: "Math Problem Identification",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MPRBID.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Demonstrated understanding of age-/grade-appropriate math problem-solving tasks",
      "Had difficulty identifying what was wrong or missing from problems",
      "Did not demonstrate understanding of age-/grade-appropriate math problem-solving tasks",
      "None of the above",
      "Identified what was wrong or missing from problems with relative ease",
    ],
  },
];
