interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  /*-----------------------------------------Ages 4 to 6 Test Items Scenarios-----------------------------------------------------*/
  {
    typeOfTest: "Ages 4 to 6 - Practice Exercise Score Entry Equal To Zero",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y5m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Practice Exercise Score Entry More Than Zero",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: [],
  },
  {
    typeOfTest: "Ages 4 to 6 - Page Score Entry With All Zero",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y5m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Page Score Entry With All Eighty",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Total Score Entry",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y6m",
    GE: "G5.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Edit Scores Scenario",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y5m",
    GE: "GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Score Entry After Clicking On Score Later Button",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y0m",
    GE: "G2.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 4 to 6 - Score Entry When End Test Modal Is Closed",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y9m",
    GE: "G3.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  /*-----------------------------------------Ages 7 to Adult Test Items Scenarios-----------------------------------------------------*/
  {
    typeOfTest: "Ages 7 to Adult - Page Score Entry With All Zero",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y5m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 7 to Adult - Page Score Entry With All Eighty",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 7 to Adult - Total Score Entry",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y6m",
    GE: "G5.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 7 to Adult - Edit Scores Scenario",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y5m",
    GE: "GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest:
      "Ages 7 to Adult - Score Entry After Clicking On Score Later Button",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y0m",
    GE: "G2.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
  {
    typeOfTest: "Ages 7 to Adult - Score Entry When End Test Modal Is Closed",
    testName: "Math Facts Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "MTHFLU.W5PA",
    lookUpModel: "SingleTable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y9m",
    GE: "G3.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Performed consistently across addition, subtraction, and multiplication facts",
      "Refused to complete the test",
      "Demonstrated automaticity with math facts",
      "None of the above",
      "Did not demonstrate automaticity with math facts",
    ],
  },
];
