interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "All Correct SSP 1",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP2",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "B&C SSP1",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y10m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "B&C SSP2",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y1m",
    GE: "GK.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "B&C SSP3",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y2m",
    GE: "G1.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "B&C SSP4",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y11m",
    GE: "G2.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "B&C SSP5",
    testName: "Number Series",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "NUMSER.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y9m",
    GE: "G3.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used “self-talk” strategy",
      "Appeared comfortable working with numbers",
      "Controlled frustration level as the items increased in difficulty",
      "None of the above",
    ],
  },
];
