interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "All Correct SSP 1",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "All Correct SSP 6",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP1",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP2",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP3",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 7 to 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y6m",
    GE: "GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP4",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y8m",
    GE: "G1.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP5",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y4m",
    GE: "G2.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },

  {
    typeOfTest: "B&C SSP6",
    testName: "Oral Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLCMP.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "12y4m",
    GE: "G6.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Displayed good attention",
      "Had difficulty providing responses that made sense",
      "Had difficulty sustaining attention",
      "Displayed good understanding of passages",
      "None of the above",
      "Had difficulty understanding passages",
    ],
  },
];
