interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 6 to 7 - Story 1 Discontinue Scenario with RS 5",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest:
      "Ages 6 to 7 - Story 1 to Story 2 Discontinue Scenario with RS 5",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y5m",
    GE: "G1.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest:
      "Ages 6 to 7 - Story 1 to Story 3 Discontinue Scenario with RS 5",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y11m",
    GE: "G1.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest:
      "Ages 6 to 7 - Story 1 to Story 4 Discontinue Scenario with RS 5",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y6m",
    GE: "G2.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest:
      "Ages 6 to 7 - Story 1 to Story 5 Discontinue Scenario with RS 5",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y1m",
    GE: "G2.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest: "Ages 6 to 7 - Story 1 to Story 6 EndTest Scenario",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "17y5m",
    GE: ">G4.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest:
      "Age 8 to Adult - Story 3 to Story 2 & 1 logic flow & EndTest Scenario",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y9m",
    GE: "G1.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest: "Age 8 to Adult - Story 3 to Story 4 Discontinue Scenario",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y3m",
    GE: "G2.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest: "Age 8 to Adult - Story 3 to Story 5 Discontinue Scenario",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y2m",
    GE: "G3.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },

  {
    typeOfTest: "Age 8 to Adult - Story 3 to Story 6 End Test Scenario",
    testName: "Oral Reading",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLRDG.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y4m",
    GE: "G3.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Used good expression when reading",
      "Read sentences at grade-appropriate rate and level of accuracy",
      "Made several self-corrections",
      "Read sentences slowly but accurately",
      "Lacked expression when reading",
      "Read sentences slowly and inaccurately",
      "Used phonics to pronounce unfamiliar words",
      "None of the above",
      "Had difficulty using phonics to pronounce unfamiliar words",
    ],
  },
];
