interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Block A EndTest Flow when RS is 3",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block A Forward Flow when all correct",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block B EndTest Flow when RS is 3",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y9m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block B Forward Flow when RS is 4",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block AB all correct with all incorrect in Block C",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y9m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block ABC all correct",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest:
      "Block B to A routing scenario when RS is 3 with all correct in Block A",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y9m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest:
      "Block B to A routing scenario when RS is 3 with all Incorrect in Block A",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block B Forward Flow when RS is 4(ssp2)",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block BC all correct",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 6 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block C all correct",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },

  {
    typeOfTest: "Block C all Incorrect",
    testName: "Oral Language Samples",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "ORLSMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Expressed responses fluently",
      "Did not make vocabulary and grammar errors",
      "Had difficulty expressing responses fluently",
      "Made vocabulary and grammar errors",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Did not display age-appropriate speech and articulation",
    ],
  },
];
