interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 8 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 8 - Basal and ceiling with 5 incorrect scenario SSP1",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 8 -  5 correct and 5 incorrect scenario",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 8 - All correct scenario",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 8",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    /*---------------------------------------------Ages 9 to 13 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 9 to 13 -  5 correct and 5 incorrect scenario",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 9 to 13 - Reverse logic with 5 incorrect scenario SSP2",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 9 to 13 - All correct scenario ",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 9 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
     /*---------------------------------------------Age 14 to Average Adult---------------------------------------------------*/
    {
        typeOfTest: "Age 14 to Average Adult -  5 correct and 5 incorrect scenario",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 14 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Age 14 to Average Adult - Reverse logic with 5 incorrect scenario SSP3",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 14 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Age 14 to Average Adult - All correct scenario ",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Age 14 to Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
      /*---------------------------------------------Above Average Adult Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Above Average Adult -  5 correct and 5 incorrect scenario",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Above Average Adult - Reverse logic with 5 incorrect scenario SSP4",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Above Average Adult - All correct scenario ",
        testName: "Oral Vocabulary–Antonyms",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "OVANT.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Above Average Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "–",
        GE: "–",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Retrieved words fluently",
            "Demonstrated good understanding of vocabulary",
            "Displayed age-appropriate speech and articulation",
            "None of the above",
        ],
    },
]