interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Block A EndTest Flow when RS is 3",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y3m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block A to B routing scenario when RS is 4 in Block A and Block AB EndTest check when RS is 15",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y11m",
    GE: "G2.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block A to B to C routing scenario when RS is 5 in Block A and Block ABC EndTest check when RS is 16 with all correct in Block C",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "11y6m",
    GE: "G6.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block A to B to C routing scenario when RS is 5 in Block A and Block ABC EndTest check when RS is 16 with all Incorrect in Block C",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y2m",
    GE: "G1.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block B to A routing scenario when RS is 6 in Block B and Block AB EndTest check with all correct in Block A",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y9m",
    GE: "G1.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block B to A routing scenario when RS is 6 in Block B and Block AB EndTest check with all Incorrect in Block A",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y5m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block B to C routing scenario when RS is 7 in Block B and Block BC EndTest check when RS is 17",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y11m",
    GE: "G3.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block B to C to D routing scenario when RS is 10 in Block B and Block BCD EndTest check when RS is 20 with all correct in Block D",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "18y5m",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block B to C to D routing scenario when RS is 10 in Block B and Block BCD EndTest check when RS is 20 with all Incorrect in Block D",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y11m",
    GE: "G3.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to B routing scenario when RS is 4 in Block C and Block BC EndTest check with all correct in Block B",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y3m",
    GE: "G2.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to B routing scenario when RS is 4 in Block C and Block BC EndTest check with all Incorrect in Block B",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y8m",
    GE: "GK.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to B routing scenario when RS is 0 in Block C and routing check to Block A when RS is 1 in Block B and Block ABC EndTest check with all correct in Block A",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y7m",
    GE: "GK.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to B routing scenario when RS is 0 in Block C and routing check to Block A when RS is 1 in Block B and Block ABC EndTest check with all Incorrect in Block A",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to D routing scenario when RS is 5 in Block C and Block CD EndTest check when RS is 15",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y8m",
    GE: "G5.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to D to E routing scenario when RS is 9 in Block C and Block CDE EndTest check when RS is 19 with all correct in Block E",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">28y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block C to D to E routing scenario when RS is 9 in Block C and Block CDE EndTest check when RS is 19 with all Incorrect in Block E",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y9m",
    GE: "G5.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to C routing scenario when RS is 4 in Block D and Block CD EndTest check with all correct in Block C",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y3m",
    GE: "G4.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to C routing scenario when RS is 4 in Block D and Block CD EndTest check with all Incorrect in Block C",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y5m",
    GE: "G2.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to C routing scenario when RS is 0 in Block D and routing check to Block B when RS is 1 in Block C and Block BCD EndTest check with all correct in Block B",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y4m",
    GE: "G1.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to C routing scenario when RS is 0 in Block D and routing check to Block B when RS is 1 in Block C and Block BCD EndTest check with all Incorrect in Block B",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y7m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to E routing scenario when RS is 5 in Block D and Block DE EndTest check with all correct in Block E",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "16y4m",
    GE: "G10.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest:
      "Block D to E routing scenario when RS is 5 in Block D and Block DE EndTest check with all Incorrect in Block E",
    testName: "Paragraph Reading Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PARCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 9 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y11m",
    GE: "G3.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading the passages",
      "Had difficulty providing responses that made sense",
      "Reviewed the passage to find answers to the questions",
      "Appeared to read the passages with no difficulty",
      "None of the above",
    ],
  },
];
