interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Block A EndTest Flow when RS is 3",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y8m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Block A forward flow scenario when RS is 4",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block A forward flow scenario with all items correct",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block AB All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 7 All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Ages 8 to 9 All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Ages 10 to 11 All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 12 to Average Adult All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Above Average Adult All Correct Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 7 Basal & Ceiling scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y11m",
    GE: "G1.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Ages 8 to 9 Basal & Ceiling scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y10m",
    GE: "G2.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Ages 10 to 11 Basal & Ceiling scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y8m",
    GE: "G3.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 12 to Average Adult Basal & Ceiling scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y8m",
    GE: "G4.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Above Average Adult Basal & Ceiling scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "16y4m",
    GE: "G10.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Age 7 Review Flow Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 8 to 9 Review Flow Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 10 to 11 Review Flow Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Age 12 to Average Adult Review Flow Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Above Average Adult Review Flow Scenario",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y8m",
    GE: "GK.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y8m",
    GE: "GK.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y8m",
    GE: "GK.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Passage Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "PSGCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y8m",
    GE: "GK.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Provided responses that made sense",
      "Appeared to have difficulty reading passages",
      "Had difficulty providing responses that made sense",
      "Reread the passage to help determine the correct response",
      "Appeared to read passages with no difficulty",
      "None of the above",
    ],
  },
];
