interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 4 to 7 - Sample Items End Test Flow scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },

  {
    typeOfTest: "Ages 8 to Adult - Sample Items End Test Flow scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },

  {
    typeOfTest: "Ages 4 to 7 - Test Items All correct scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },

  {
    typeOfTest: "Ages 8 to Adult - Test Items All correct scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },

  {
    typeOfTest: "Ages 4 to 7 - Test Items 10 incorrect scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
  {
    typeOfTest: "Ages 8 to Adult - Test Items 10 incorrect scenario",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
  {
    typeOfTest: "Ages 4 to 7 - When Timer Ran Out for First Item set",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 0",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
  {
    typeOfTest: "Ages 8 to Adult - When Timer Ran Out for First Item set",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 0",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
  {
    typeOfTest: "Ages 4 to 7 - Test Items When Timer Ran Out for Last Item set",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 0",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
  {
    typeOfTest: "Ages 8 to Adult - Test Items When Timer Ran Out for Last Item set",
    testName: "Rapid Letter Naming",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "RPDLET.W5PA",
    lookUpModel: "DecileTable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 0",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Test timer ran out.",
    responseStyleBehaviours: [
      "Made errors on some letters",
      "Displayed balance between speed and accuracy",
      "Displayed sustained concentration and effort throughout this test",
      "None of the above",
      "Had difficulty sustaining concentration and effort throughout this test",
    ],
  },
];
