interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 4 to 5 - All correct scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">27y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Age 6 - All correct scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">27y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 7 to Adult - All correct scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">27y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 4 to 5 - All Incorrect scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Age 6 - All Incorrect scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 7 to Adult - All Incorrect scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 4 to 5 - Discontinue Scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y5m",
    GE: "G1.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },
 
  {
    typeOfTest: "Age 6 - Discontinue Scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y5m",
    GE: "G1.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },
  
  {
    typeOfTest: "Ages 7 to Adult - Discontinue Scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y5m",
    GE: "G1.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Age 6 - Block B incorrect and Block A correct Scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y11m",
    GE: "GK.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 7 to Adult - Block C incorrect and Block B correct Scenario",
    testName: "Segmentation",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SEGMNT.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y11m",
    GE: "G2.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved segmenting phonemes",
      "None of the above",
      "Had difficulty completing items that involved segmenting phonemes",
    ],
  },

];
