interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 4 to 5 - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Age 6 - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Age 7 - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Ages 8 to 9 - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Ages 10 to Average Adult - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Above Average Adult - All correct scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },
  {
    typeOfTest: "Ages 4 to 5 - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 5",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Age 6 - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Age 7 - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Ages 8 to 9 - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Ages 10 to Average Adult - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest: "Above Average Adult - All Incorrect scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },
  {
    typeOfTest: "Age 6 - Basal and ceiling scenario with 4 incorrect",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y2m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },
  {
    typeOfTest: "Age 7 - Reverse logic scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

 {
    typeOfTest:
      "Ages 8 to 9 - Reverse logic scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest:
      "Ages 10 to Average Adult - Reverse logic scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },

  {
    typeOfTest:
      "Above Average Adult - Reverse logic scenario",
    testName: "Sentence Repetition",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SENREP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Repeated age-appropriate sentences accurately",
      "Made several errors and did not maintain the meaning of the sentence",
      "Did not repeat age-appropriate sentences accurately",
      "None of the above",
      "Made minor errors but maintained the meaning of the sentence",
    ],
  },
];
