interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 13 Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 4 to 13 - Basal and ceiling with 5 incorrect scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y1m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 13 -  5 correct and 5 incorrect scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "8y6m",
        GE: "G3.1",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 13 - All correct scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">25y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 4 to 13 - Review flow Scenario for SSP1",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 4 to 13",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "5y2m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    /*---------------------------------------------Ages 14 to Adult Scenarios---------------------------------------------------*/
    {
        typeOfTest: "Ages 14 to Adult - Basal and ceiling with 5 incorrect scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "4y1m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult -  5 correct and 5 incorrect scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "11y0m",
        GE: "G5.6",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult - Reverse logic with 5 correct and 5 incorrect scenario",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "11y0m",
        GE: "G5.6",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult - All correct scenario ",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: ">25y",
        GE: ">G12.9",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
           "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },
    {
        typeOfTest: "Ages 14 to Adult - Review flow Scenario for SSP2",
        testName: "Sound Reversal",
        blockName: "Form A",
        examineeAge: 4,
        testStemForm: "SNDREV.W5PA",
        lookUpModel: "SingleTable",
        SSP: "Ages 14 to Adult",
        location: "PVP",
        examineeGrade: "Grade 4",
        AE: "5y2m",
        GE: "<GK.0",
        ScoreCheckStatus: "Test Complete",
        FlagStatus: "0 items",
        OutcomeText: "Examinee completed all required test items.",
        responseStyleBehaviours: [
            "Was able to pronounce sounds in reverse order",
            "Displayed good attention",
            "Used memory strategies (rehearsal, chunking, visualization)",
            "None of the above",
        ],
    },

]