interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Ages 4 to 7 - All correct scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">23y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest: "Ages 4 to 7 - Sample item AB Discontinue scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  },

  {
    typeOfTest: "Ages 4 to 7 - Sample item AB forward scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  },  

  {
    typeOfTest: "Ages 4 to 7 - Block A end test scenario with RS 3",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest: "Ages 4 to 7 - Block A forward scenario with RS 4",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest:
      "Ages 8 to Adult - Sample item CD Routing back to Intro 1 Scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest: "Ages 8 to Adult - Sample item CD Forward Scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest:
      "Ages 8 to Adult - Block B Routing back to Intro 1 with RS 4 Scenario",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 

  {
    typeOfTest:
      "Ages 8 to Adult - Block B Forward to Block C Scenario with RS 5 ",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y9m",
    GE: "GK.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  },

  {
    typeOfTest:
      "Ages 8 to Adult - Block B to Block C End test Scenario with RS 5",
    testName: "Sound Substitution",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SNDSUB.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y6m",
    GE: "G1.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Displayed good phonological awareness skills",
      "Displayed good attention",
      "Displayed poor phonological awareness skills",
      "Had difficulty sustaining attention",
      "Completed items that involved substituting phonemes",
      "None of the above",
      "Had difficulty completing items that involved substituting phonemes",
    ],
  }, 
];
