interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "All Correct SSP 1",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 6",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 7",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "All Correct SSP 8",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP2",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP7",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP8",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP1",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y2m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP2",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y4m",
    GE: "GK.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP3",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y6m",
    GE: "G2.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP4",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 9 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y2m",
    GE: "G2.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP5",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y9m",
    GE: "G3.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP6",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y8m",
    GE: "G4.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP7",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y3m",
    GE: "G4.8",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },

  {
    typeOfTest: "B&C SSP8",
    testName: "Spelling",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "SPELL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "15y9m",
    GE: "G10.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Spelled words easily and accurately",
      "Spelled words phonetically",
      "Had difficulty spelling words",
      "None of the above",
      "Reversed one or more letters",
    ],
  },
];
