interface TestData {
    typeOfTest: string;
    testName: string;
    blockName: string;
    examineeAge: number;
    SSP: string;
    BbyC?: number;
    testStemForm: string;
    lookUpModel: string;
    negation?: boolean;
    location?: string;
    examineeGrade: string,
    AE: string;
    GE: string;
    ScoreCheckStatus: string;
    FlagStatus: string;
    OutcomeText: string;
    responseStyleBehaviours: string[];
  }
  
  export const testData: TestData[] = [
    /*---------------------------------------------Ages 4 to 6 Scenarios---------------------------------------------------*/
    {
      typeOfTest: "Ages 4 to 6 - Sample Items End Test Flow scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "4y7m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee did not meet continuation requirements.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
   {
      typeOfTest: "Ages 4 to 6 - Block A End Test Scenario With All incorrect",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "<4y0m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 4 to 6 - Block A, Block B and Block C All correct Scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">23y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 4 to 6 - Block A All correct and Block B All incorrect Scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "<4y0m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 4 to 6 - Block A, Block B All correct and Block C All incorrect Scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">23y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
   {
      typeOfTest: "Ages 4 to 6 - Block A Review Flow Logic",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 4 to 6",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "5y8m",
      GE: "GK.3",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    /*---------------------------------------------Ages 7 to Adult Scenarios---------------------------------------------------*/
    {
      typeOfTest: "Ages 7 to Adult - Block B and Block C All correct Scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 7 to Adult",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">23y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 7 to Adult - Block B All incorrect Scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 7 to Adult",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "<4y0m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 7 to Adult - Block B All correct scenario",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 7 to Adult",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">23y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
    {
      typeOfTest: "Ages 7 to Adult - Block B Review Flow Logic",
      testName: "Spelling of Sounds",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SPLSND.W5PA",
      lookUpModel:"Multitable",
      SSP: "Ages 7 to Adult",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "4y8m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee completed all required test items.",
      responseStyleBehaviours: [
        "Demonstrated good orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are possible in English)",
        "Had difficulty spelling pseudowords",
        "Did not demonstrate orthographic knowledge when spelling pseudowords (e.g., used letter combinations that are uncommon in English)",
        "None of the above",
        "Spelled pseudowords easily and accurately",
      ],
    },
   
]