interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Sample Item EndTest Flow when RS is 0",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Sample Item EndTest Flow when RS is 1",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Sample Item Forward Flow when RS is 2",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block A EndTest Flow When RS is 5",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block A to Block B Forward Flow When RS is 6 and Block AB EndTest Scenario",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block B to Block A routing flow When RS is 5 in Block B and all correct in Block A",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block B to Block A routing flow When RS is 5 in Block B and all incorrect in Block A",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y1m",
    GE: "G3.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block B to Block C Forward flow When RS is 9 in Block B and all correct in Block C",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block B to Block C Forward flow When RS is 9 in Block B and all incorrect in Block C",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 8 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "12y7m",
    GE: "G7.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest: "Block C to Block B routing flow When RS is 0 in Block C and all correct in Block B",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "12y7m",
    GE: "G7.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block C to Block B routing flow When RS is 0 in Block C and all incorrect in Block B",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block C to Block D Forward flow When RS is 13 in Block C and all correct in Block D",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block C to Block D Forward flow When RS is 13 in Block C and all incorrect in Block D",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block D to Block C routing flow When RS is 0 in Block D and all correct in Block C",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block D to Block C routing flow When RS is 0 in Block D and all incorrect in Block C",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block D to Block E Forward flow When RS is 13 in Block D and all correct in Block E",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },

  {
    typeOfTest:"Block D to Block E Forward flow When RS is 13 in Block D and all incorrect in Block E",
    testName: "Story Comprehension",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYCMP.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Was able to answer questions correctly",
      "Displayed good attention",
      "Had difficulty answering questions",
      "Had difficulty sustaining attention",
      "Recalled most information from stories",
      "None of the above",
      "Had difficulty recalling information from stories",
    ],
  },
];
