interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Story 1&2 EndTest Flow when RS is 4",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y5m",
    GE: "G2.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest: "Story 1&2 forward Flow to Story 3 when RS is 10",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", ""],
  },

  {
    typeOfTest: "Story 1 to 4 End Test Flow when RS is 17",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "12y6m",
    GE: "G7.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest: "Story 1 to 4 forward Flow to Story 5 when RS is 24",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", ""],
  },

  {
    typeOfTest: "Story 1 to 6 End Test Flow with all correct",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 3 and 4 to 1 and 2 End Test Flow with RS 4 in stories 3&4",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y11m",
    GE: "G5.5",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 3 to 6 EndTest Scenario with RS 7 in stories 3&4 and RS 23 in 3to6",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y0m",
    GE: "G2.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest: "Story 3 to 8 End Test Flow with all correct",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 7 to 10",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 5 and 6 to 3 and 4 End Test Flow with RS 7 in stories 5&6 and RS 21 in 3to6",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y9m",
    GE: "G2.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 5 and 6 to 3 and 4 and to 1 and 2 End Test Flow with RS 1 in stories 5&6 and RS 1 in 3to6",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y8m",
    GE: "G4.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 5 and 6 to 7 and 8 End Test Flow with RS 8 in stories 5&6 and RS 39 in 5to8",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest: "Story 5 to 10 End Test Flow with all correct",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 11 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 7 and 8 to 5 and 6 End Test Flow with RS 13 in stories 7&8 and RS 29 in 5to8",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "13y1m",
    GE: "G7.7",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest:
      "Story 7 and 8 to 5 and 6 and to 3 and 4 End Test Flow with RS 1 in stories 7&8 and RS 1 in 5to8",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y10m",
    GE: "G1.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },

  {
    typeOfTest: "Story 7 to 10 End Test Flow with all correct",
    testName: "Story Recall",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "STYREC.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 14 to Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Errors made sense in context of story",
      "Used memory strategies (mnemonics, elaboration, chunking)",
      "Recalled elements in the sequence presented in the story",
      "None of the above",
      "Recalled elements but out of sequence",
    ],
  },
];
