interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
      typeOfTest: "All Examinees - Sample Items End Test Flow scenario",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "5y2m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee did not meet continuation requirements.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Page Score Entry With All Zero",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "5y2m",
      GE: "<GK.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Page Score Entry With All Eight",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">27y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Total Score Entry",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "16y5m",
      GE: "G11.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Edit Scores Scenario",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4,
      testStemForm: "SWRTFL.W5PA",
      lookUpModel: "SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "9y0m",
      GE: "G3.6",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Page Score Entry After Clicking On Stop Timer Button",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">27y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Examinee did not meet continuation requirements.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Page Score Entry After Clicking On Cancel Button",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: "16y5m",
      GE: "G11.0",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Score Entry After Clicking On Score Later Button",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">27y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
    {
      typeOfTest: "All Examinees - Score Entry When End Test Modal Is Closed",
      testName: "Sentence Writing Fluency",
      blockName: "Form A",
      examineeAge: 4, 
      testStemForm: "SWRTFL.W5PA",
      lookUpModel:"SingleTable",
      SSP: "All Examinees",
      location: "PVP",
      examineeGrade: "Grade 4",
      AE: ">27y",
      GE: ">G12.9",
      ScoreCheckStatus: "Test Complete",
      FlagStatus: "0 items",
      OutcomeText: "Test timer ran out.",
      responseStyleBehaviours: [
        "Wrote sentences that were inadequate (e.g., incomplete, illegible, syntax errors, did not meet task demands)",
        "Had difficulty sustaining concentration and effort throughout this test",
        "Demonstrated adequate basic writing skills (e.g., spelling, punctuation, capitalization)",
        "Composed sentences quickly",
        "Made errors in basic writing skills",
        "Composed sentences slowly",
        "Wrote simple sentences that used all three words correctly",
        "Refused to complete the test",
        "Displayed sustained concentration and effort throughout this test",
        "None of the above",
      ],
    },
];
