interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "All Correct SSP 1",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "All Correct SSP 2",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "All Correct SSP 3",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 8 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "All Correct SSP 4",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "All Correct SSP 5",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">29y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP2",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 8 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "B&C SSP1",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 4 to 6",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "4y4m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "B&C SSP2",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y7m",
    GE: "GK.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "B&C SSP3",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Ages 8 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y4m",
    GE: "G1.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "B&C SSP4",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Age 12 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y5m",
    GE: "G3.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },

  {
    typeOfTest: "B&C SSP5",
    testName: "Verbal Analogies",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "VRBANL.W5PA",
    lookUpModel: "Singletable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y8m",
    GE: "G5.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Retrieved words fluently",
      "Demonstrated good understanding of the relationships among the words",
      "Displayed age-appropriate speech and articulation",
      "None of the above",
      "Demonstrated good understanding of vocabulary",
    ],
  },
];
