interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Block A EndTest Flow when RS is 2",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y1m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Block B EndTest Flow with RS of 3 in Block A and 0 in Block B",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "5y4m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Block A & B forward flow scenario when RS is 4",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block A & B forward flow scenario with all items correct",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Block ABC All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 4 to 7",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Age 8 All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Age 9 All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 10 to 11 All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 12 to 13 All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 14 to Average Adult All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Above Average Adult All Correct Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">26y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Age 8 Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y9m",
    GE: "G1.3",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Age 9 Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y3m",
    GE: "G1.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 10 to 11 Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "7y10m",
    GE: "G2.4",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 12 to 13 Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "8y7m",
    GE: "G3.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Ages 14 to Average Adult Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "9y5m",
    GE: "G4.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Above Average Adult Basal & Ceiling scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "10y6m",
    GE: "G5.1",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Age 8 Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 8",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Age 9 Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 10 to 11 Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 12 to 13 Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Ages 14 to Average Adult Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Above Average Adult Review Flow Scenario",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Reverse Logic for SSP3",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Age 9",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y7m",
    GE: "G1.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP4",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 10 to 11",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y7m",
    GE: "G1.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP5",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 12 to 13",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y7m",
    GE: "G1.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP6",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Ages 14 to Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y7m",
    GE: "G1.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },

  {
    typeOfTest: "Reverse Logic for SSP7",
    testName: "Word Attack",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDATK.W5PA",
    lookUpModel: "Multitable",
    SSP: "Above Average Adult",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "6y7m",
    GE: "G1.2",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Made several self-corrections",
      "Applied phonics to pseudowords",
      "Read pseudowords accurately with ease",
      "Had difficulty applying phonics to pseudowords",
      "Had difficulty reading pseudowords accurately with ease",
      "None of the above",
      "Pronounced initial sounds of some words correctly",
    ],
  },
];
