interface TestData {
  typeOfTest: string;
  testName: string;
  blockName: string;
  examineeAge: number;
  SSP: string;
  BbyC?: number;
  testStemForm: string;
  lookUpModel: string;
  negation?: boolean;
  location?: string;
  examineeGrade: string;
  AE: string;
  GE: string;
  ScoreCheckStatus: string;
  FlagStatus: string;
  OutcomeText: string;
  responseStyleBehaviours: string[];
}

export const testData: TestData[] = [
  {
    typeOfTest: "Sample Item EndTest Flow when RS is 0",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },

  {
    typeOfTest: "Sample Item EndTest Flow when RS is 1",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },

  {
    typeOfTest: "Sample Item Forward Flow when RS is 2",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Practice Exercise All Incorrect",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee did not meet continuation requirements.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },

  {
    typeOfTest: "Practice Exercise All Correct",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Practice Exercise 2 Correct",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest:
      "Practice Exercise InCorrect to All Correct in Practice Feedback",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "",
    GE: "",
    ScoreCheckStatus: "",
    FlagStatus: "",
    OutcomeText: "",
    responseStyleBehaviours: ["", "", "", "", "", "", ""],
  },

  {
    typeOfTest: "Test Items All Correct",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: ">28y",
    GE: ">G12.9",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },

  {
    typeOfTest: "Test Items All Incorrect",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "<4y0m",
    GE: "<GK.0",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },

  {
    typeOfTest: "Test Items 6 Correct",
    testName: "Word Reading Fluency",
    blockName: "Form A",
    examineeAge: 4,
    testStemForm: "WRDGFL.W5PA",
    lookUpModel: "SingleTable",
    SSP: "All Examinees",
    location: "PVP",
    examineeGrade: "Grade 4",
    AE: "16y0m",
    GE: "G10.6",
    ScoreCheckStatus: "Test Complete",
    FlagStatus: "0 items",
    OutcomeText: "Examinee completed all required test items.",
    responseStyleBehaviours: [
      "Appeared to mark responses carefully",
      "Appeared to read words slowly but accurately",
      "Appeared to mark responses randomly without a strategy",
      "Appeared to read words slowly and inaccurately",
      "Appeared to read words quickly and accurately",
      "None of the above",
      "Appeared to read words quickly but inaccurately",
    ],
  },
];
