interface TestData {
  typeOfTest: string;
  testNumber: number[];
  testName: string[];
  testStemForm: string[];
  taskStem: string[];
  blockName: string;
  examineeGrade: string;
  lookUpModel: string;
}

export const testData: TestData[] = [
  // --------------   ---------------------------------------

  {
    typeOfTest: "basal and ceiling",
    testNumber: [1, 2], // Not much useful for time being
    testName: [
      "Analysis-Synthesis",
      "Block Rotation",
      "Letter-Pattern Matching",
      "Number-Pattern Matching",
      "Matrices",
      "Phonemic Word Retrieval",
      "Semantic Word Retrieval",
      "Spatial Relations",
      "Oral Vocabulary–Synonyms",
      "Oral Vocabulary–Antonyms",
      "Story Comprehension",
      "Story Recall",
      "Verbal Analogies",
      "Verbal Attention",
      "Spelling of Sounds",
      "Sentence Reading Fluency",
      "Sentence Writing Fluency",
      "Word Attack",
      "Word Reading Fluency",
      "Written Language Samples",
      "Sentence Writing Accuracy",
      "Applied Problems",
      "Calculation",
      "Oral Language Samples",
      "Letter-Word Identification",
      "Math Problem Identification",
      "Math Facts Fluency",
      "Oral Comprehension",
      "Paragraph Reading Comprehension",
      "Picture Vocabulary",
      "Passage Comprehension",
    ],
    testStemForm: [
      "ANLSYN.W5PA",
     "BLKROT.W5PA",
      "LETPAT.W5PA",
      "NUMPAT.W5PA",
      "MATRCZ.W5PA",
      "PHNRET.W5PA",
      "SEMRET.W5PA",
      "SPAREL.W5PA",
      "OVANT.W5PA",
      "OVSYN.W5PA",
      "STYCMP.W5PA",
      "STYREC.W5PA",
      "VRBANL.W5PA",
      "VRBATN.W5PA",
      "SPELL.W5PA",
      "SRDGFL.W5PA",
      "SWRTFL.W5PA",
      "WRDATK.W5PA",
      "WRDGFL.W5PA",
      "WRTSMP.W5PA",
      "SWRTAC.W5PA",
      "APPROB.W5PA",
      "CALC.W5PA",
      "ORLSMP.W5PA",
      "LWIDNT.W5PA",
      "MPRBID.W5PA",
      "MTHFLU.W5PA",
      "ORLCMP.W5PA",
      "PARCMP.W5PA",
      "PICVOC.W5PA",
      "PSGCMP.W5PA",
    ],
    taskStem: [
      "ANLSYN",
      "BLKROT",
      "LETPAT",
      "NUMPAT",
      "MATRCZ",
      "PHNRET",
      "SEMRET",
      "SPAREL",
      "OVANT",
      "OVSYN",
      "STYCMP",
      "STYREC",
      "VRBANL",
      "VRBATN",
      "SPELL",
      "SRDGFL",
      "SWRTFL",
      "WRDATK",
      "WRDGFL",
      "WRTSMP",
      "SWRTAC",
      "APPROB",
      "CALC",
      "ORLSMP",
      "LWIDNT",
      "MPRBID",
      "MTHFLU",
      "ORLCMP",
      "PARCMP",
      "PICVOC",
      "PSGCMP",
    ],
    blockName: "Form A",
    examineeGrade: "Grade 1",
    lookUpModel: "basal and ceiling",
  },
];
